# get shiny serves plus tidyverse packages image
FROM rocker/shiny-verse:latest

# system libraries of general use
RUN echo 'deb http://deb.debian.org/debian bullseye main' > /etc/apt/sources.list
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libcurl4-openssl-dev \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    libudunits2-dev \
    libssh2-1-dev \
    libcairo2-dev \
    sudo

# copy the app to the image
COPY ./env-variable/app.R /srv/shiny-server/
COPY shiny-server.sh /usr/bin/shiny-server.sh

EXPOSE 3838

# allow permission
RUN sudo chown -R shiny:shiny /srv/shiny-server

# run app
RUN ["chmod", "+x", "/usr/bin/shiny-server.sh"]
